services:
  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ../persistence-service/config/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - web-services

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web-services

  backend:
    build: ../persistence-service/backend
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web-services

  test:
    build:
      context: .
      dockerfile: test-setup.Dockerfile
    command: ["./scripts/run-all-tests.sh"]
    environment:
      TARGET_URL: reverse-proxy
    volumes:
      - ./results/:/results/
    networks:
      - web-services

networks:
  web-services:

volumes:
  postgres-data: